title: De Plantuh Man
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: /images/chuttersnap-9g1kxjqoq4u-unsplash-min.jpg
    has_nav: true
    has_social: true
    logo_img: /images/deplantuhman2.png
    tagline: For the Growth of The Nation
    title: De Plantuh Man
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
