title: De Plantuh Man
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: /images/muhamad-rizal-firmansyah-akeea3_skmm-unsplash.jpg
    has_nav: true
    has_social: true
    logo_img: ''
    tagline: For the Growth of The Nation
    title: De Plantuh Man
  palette: red
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
